/* tslint:disable */
/* eslint-disable */
/**
 * Tribufu API
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ApplicationType = {
    Application: 'application',
    Game: 'game'
} as const;
export type ApplicationType = typeof ApplicationType[keyof typeof ApplicationType];


export function instanceOfApplicationType(value: any): boolean {
    for (const key in ApplicationType) {
        if (Object.prototype.hasOwnProperty.call(ApplicationType, key)) {
            if (ApplicationType[key as keyof typeof ApplicationType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApplicationTypeFromJSON(json: any): ApplicationType {
    return ApplicationTypeFromJSONTyped(json, false);
}

export function ApplicationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationType {
    return json as ApplicationType;
}

export function ApplicationTypeToJSON(value?: ApplicationType | null): any {
    return value as any;
}

export function ApplicationTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ApplicationType {
    return value as ApplicationType;
}

