/* tslint:disable */
/* eslint-disable */
/**
 * Tribufu API
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CodeChallengeMethod = {
    Plain: 'plain',
    S256: 'S256'
} as const;
export type CodeChallengeMethod = typeof CodeChallengeMethod[keyof typeof CodeChallengeMethod];


export function instanceOfCodeChallengeMethod(value: any): boolean {
    for (const key in CodeChallengeMethod) {
        if (Object.prototype.hasOwnProperty.call(CodeChallengeMethod, key)) {
            if (CodeChallengeMethod[key as keyof typeof CodeChallengeMethod] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CodeChallengeMethodFromJSON(json: any): CodeChallengeMethod {
    return CodeChallengeMethodFromJSONTyped(json, false);
}

export function CodeChallengeMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): CodeChallengeMethod {
    return json as CodeChallengeMethod;
}

export function CodeChallengeMethodToJSON(value?: CodeChallengeMethod | null): any {
    return value as any;
}

export function CodeChallengeMethodToJSONTyped(value: any, ignoreDiscriminator: boolean): CodeChallengeMethod {
    return value as CodeChallengeMethod;
}

