/* tslint:disable */
/* eslint-disable */
/**
 * Tribufu API
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CryptoViewModel
 */
export interface CryptoViewModel {
    /**
     * 
     * @type {string}
     * @memberof CryptoViewModel
     */
    encoded?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CryptoViewModel
     */
    decoded?: string | null;
}

/**
 * Check if a given object implements the CryptoViewModel interface.
 */
export function instanceOfCryptoViewModel(value: object): value is CryptoViewModel {
    return true;
}

export function CryptoViewModelFromJSON(json: any): CryptoViewModel {
    return CryptoViewModelFromJSONTyped(json, false);
}

export function CryptoViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CryptoViewModel {
    if (json == null) {
        return json;
    }
    return {
        
        'encoded': json['encoded'] == null ? undefined : json['encoded'],
        'decoded': json['decoded'] == null ? undefined : json['decoded'],
    };
}

export function CryptoViewModelToJSON(json: any): CryptoViewModel {
    return CryptoViewModelToJSONTyped(json, false);
}

export function CryptoViewModelToJSONTyped(value?: CryptoViewModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'encoded': value['encoded'],
        'decoded': value['decoded'],
    };
}

