/* tslint:disable */
/* eslint-disable */
/**
 * Tribufu API
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const GroupRank = {
    Member: 'member',
    Leader: 'leader',
    Owner: 'owner'
} as const;
export type GroupRank = typeof GroupRank[keyof typeof GroupRank];


export function instanceOfGroupRank(value: any): boolean {
    for (const key in GroupRank) {
        if (Object.prototype.hasOwnProperty.call(GroupRank, key)) {
            if (GroupRank[key as keyof typeof GroupRank] === value) {
                return true;
            }
        }
    }
    return false;
}

export function GroupRankFromJSON(json: any): GroupRank {
    return GroupRankFromJSONTyped(json, false);
}

export function GroupRankFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupRank {
    return json as GroupRank;
}

export function GroupRankToJSON(value?: GroupRank | null): any {
    return value as any;
}

export function GroupRankToJSONTyped(value: any, ignoreDiscriminator: boolean): GroupRank {
    return value as GroupRank;
}

