/* tslint:disable */
/* eslint-disable */
/**
 * Tribufu API
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HashViewModel
 */
export interface HashViewModel {
    /**
     * 
     * @type {string}
     * @memberof HashViewModel
     */
    value?: string | null;
}

/**
 * Check if a given object implements the HashViewModel interface.
 */
export function instanceOfHashViewModel(value: object): value is HashViewModel {
    return true;
}

export function HashViewModelFromJSON(json: any): HashViewModel {
    return HashViewModelFromJSONTyped(json, false);
}

export function HashViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): HashViewModel {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function HashViewModelToJSON(json: any): HashViewModel {
    return HashViewModelToJSONTyped(json, false);
}

export function HashViewModelToJSONTyped(value?: HashViewModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
    };
}

