/* tslint:disable */
/* eslint-disable */
/**
 * Tribufu API
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const LeaderboardOrder = {
    Level: 'level',
    Points: 'points'
} as const;
export type LeaderboardOrder = typeof LeaderboardOrder[keyof typeof LeaderboardOrder];


export function instanceOfLeaderboardOrder(value: any): boolean {
    for (const key in LeaderboardOrder) {
        if (Object.prototype.hasOwnProperty.call(LeaderboardOrder, key)) {
            if (LeaderboardOrder[key as keyof typeof LeaderboardOrder] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LeaderboardOrderFromJSON(json: any): LeaderboardOrder {
    return LeaderboardOrderFromJSONTyped(json, false);
}

export function LeaderboardOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeaderboardOrder {
    return json as LeaderboardOrder;
}

export function LeaderboardOrderToJSON(value?: LeaderboardOrder | null): any {
    return value as any;
}

export function LeaderboardOrderToJSONTyped(value: any, ignoreDiscriminator: boolean): LeaderboardOrder {
    return value as LeaderboardOrder;
}

