/* tslint:disable */
/* eslint-disable */
/**
 * Tribufu API
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ResponseType = {
    Code: 'code',
    Token: 'token'
} as const;
export type ResponseType = typeof ResponseType[keyof typeof ResponseType];


export function instanceOfResponseType(value: any): boolean {
    for (const key in ResponseType) {
        if (Object.prototype.hasOwnProperty.call(ResponseType, key)) {
            if (ResponseType[key as keyof typeof ResponseType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ResponseTypeFromJSON(json: any): ResponseType {
    return ResponseTypeFromJSONTyped(json, false);
}

export function ResponseTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseType {
    return json as ResponseType;
}

export function ResponseTypeToJSON(value?: ResponseType | null): any {
    return value as any;
}

export function ResponseTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ResponseType {
    return value as ResponseType;
}

