/* tslint:disable */
/* eslint-disable */
/**
 * Tribufu API
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SearchType = {
    User: 'user',
    Group: 'group',
    Server: 'server',
    Cluster: 'cluster'
} as const;
export type SearchType = typeof SearchType[keyof typeof SearchType];


export function instanceOfSearchType(value: any): boolean {
    for (const key in SearchType) {
        if (Object.prototype.hasOwnProperty.call(SearchType, key)) {
            if (SearchType[key as keyof typeof SearchType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SearchTypeFromJSON(json: any): SearchType {
    return SearchTypeFromJSONTyped(json, false);
}

export function SearchTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchType {
    return json as SearchType;
}

export function SearchTypeToJSON(value?: SearchType | null): any {
    return value as any;
}

export function SearchTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): SearchType {
    return value as SearchType;
}

