/* tslint:disable */
/* eslint-disable */
/**
 * Tribufu API
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ServerStatus = {
    Unknown: 'unknown',
    Offline: 'offline',
    Online: 'online'
} as const;
export type ServerStatus = typeof ServerStatus[keyof typeof ServerStatus];


export function instanceOfServerStatus(value: any): boolean {
    for (const key in ServerStatus) {
        if (Object.prototype.hasOwnProperty.call(ServerStatus, key)) {
            if (ServerStatus[key as keyof typeof ServerStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ServerStatusFromJSON(json: any): ServerStatus {
    return ServerStatusFromJSONTyped(json, false);
}

export function ServerStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerStatus {
    return json as ServerStatus;
}

export function ServerStatusToJSON(value?: ServerStatus | null): any {
    return value as any;
}

export function ServerStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ServerStatus {
    return value as ServerStatus;
}

