/* tslint:disable */
/* eslint-disable */
/**
 * Tribufu API
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TokenType = {
    Bearer: 'bearer'
} as const;
export type TokenType = typeof TokenType[keyof typeof TokenType];


export function instanceOfTokenType(value: any): boolean {
    for (const key in TokenType) {
        if (Object.prototype.hasOwnProperty.call(TokenType, key)) {
            if (TokenType[key as keyof typeof TokenType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TokenTypeFromJSON(json: any): TokenType {
    return TokenTypeFromJSONTyped(json, false);
}

export function TokenTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenType {
    return json as TokenType;
}

export function TokenTypeToJSON(value?: TokenType | null): any {
    return value as any;
}

export function TokenTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): TokenType {
    return value as TokenType;
}

