/* tslint:disable */
/* eslint-disable */
/**
 * Tribufu API
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TokenHintType = {
    AccessToken: 'access_token',
    RefreshToken: 'refresh_token'
} as const;
export type TokenHintType = typeof TokenHintType[keyof typeof TokenHintType];


export function instanceOfTokenHintType(value: any): boolean {
    for (const key in TokenHintType) {
        if (Object.prototype.hasOwnProperty.call(TokenHintType, key)) {
            if (TokenHintType[key as keyof typeof TokenHintType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TokenHintTypeFromJSON(json: any): TokenHintType {
    return TokenHintTypeFromJSONTyped(json, false);
}

export function TokenHintTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenHintType {
    return json as TokenHintType;
}

export function TokenHintTypeToJSON(value?: TokenHintType | null): any {
    return value as any;
}

export function TokenHintTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): TokenHintType {
    return value as TokenHintType;
}

