/* tslint:disable */
/* eslint-disable */
/**
 * Tribufu API
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProfile
 */
export interface UpdateProfile {
    /**
     * 
     * @type {string}
     * @memberof UpdateProfile
     */
    displayName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfile
     */
    biography?: string | null;
}

/**
 * Check if a given object implements the UpdateProfile interface.
 */
export function instanceOfUpdateProfile(value: object): value is UpdateProfile {
    return true;
}

export function UpdateProfileFromJSON(json: any): UpdateProfile {
    return UpdateProfileFromJSONTyped(json, false);
}

export function UpdateProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'biography': json['biography'] == null ? undefined : json['biography'],
    };
}

export function UpdateProfileToJSON(json: any): UpdateProfile {
    return UpdateProfileToJSONTyped(json, false);
}

export function UpdateProfileToJSONTyped(value?: UpdateProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'display_name': value['displayName'],
        'biography': value['biography'],
    };
}

